// Generated by CoffeeScript 1.10.0
(function() {
  var MAX, ROTATION, SCALE, UNIQUE_ID, ZOUTI, Zouti, audioSelect, errorCallback, gotSources, start, successCallback, up, videoElement, videoSelect;

  SCALE = 1;

  ROTATION = 0;

  UNIQUE_ID = 1;

  MAX = 0;

  ZOUTI = ["equerre", "regle", "cercle", "rapporteur-180", "rapporteur-360", "grille", "couleurs", "pied-a-coulisse", "trigo"];

  videoElement = "";

  audioSelect = "";

  videoSelect = "";

  gotSources = function(sourceInfos) {
    var i, option, results, sourceInfo;
    i = 0;
    results = [];
    while (i !== sourceInfos.length) {
      sourceInfo = sourceInfos[i];
      option = document.createElement('option');
      option.value = sourceInfo.id;
      if (sourceInfo.kind === 'audio') {
        option.text = sourceInfo.label || 'microphone ' + audioSelect.length + 1;
        audioSelect.appendChild(option);
      } else if (sourceInfo.kind === 'video') {
        option.text = sourceInfo.label || 'camera ' + videoSelect.length + 1;
        videoSelect.appendChild(option);
      } else {
        console.log('Some other kind of source: ', sourceInfo);
      }
      results.push(++i);
    }
    return results;
  };

  successCallback = function(stream) {
    window.stream = stream;
    return videoElement.src = window.URL.createObjectURL(stream);
  };

  errorCallback = function(error) {
    return console.log('navigator.getUserMedia error: ', error);
  };

  start = function() {
    var audioSource, constraints, videoSource;
    if (window.stream) {
      videoElement.src = null;
      window.stream.stop();
    }
    audioSource = audioSelect.value;
    videoSource = videoSelect.value;
    constraints = {
      audio: {
        optional: [
          {
            sourceId: audioSource
          }
        ]
      },
      video: {
        optional: [
          {
            sourceId: videoSource
          }
        ]
      }
    };
    return navigator.getUserMedia(constraints, successCallback, errorCallback);
  };

  up = function($element) {
    var id;
    id = $element.attr("id");
    $("#delete").attr("data-id", "" + id);
    $("#delete").show();
    $(".zouti").removeClass("selected").css({
      zIndex: 0
    });
    $element.addClass("selected").css({
      zIndex: 1
    });
    setTimeout((function() {
      return $("#delete").hide();
    }), 5000);
    $("#slider-s").slider("value", $element.attr("data-scale"));
    $("#scale-info").html("x" + ($element.attr('data-scale')));
    $("#slider-r").slider("value", $element.attr("data-rotation"));
    return $("#rotation-info").html(($element.attr('data-rotation')) + "°");
  };

  Zouti = (function() {
    function Zouti(zouti1) {
      var creation, id, offset;
      this.zouti = zouti1;
      $("#delete").attr("data-id", "" + this.id);
      if (!$("#Zouti").length) {
        $("#web-iframe").after("<div id='Zouti'></div>");
      }
      creation = function(id, zouti, $parent, s, r) {
        var html, img;
        html = "<div id='" + id + "' class='zouti' data-zouti='" + zouti + "' data-scale='" + s + "' data-rotation='" + r + "'></div>";
        $parent.append(html);
        img = new Image;
        img.onload = function() {
          return $("#" + id).css({
            width: img.width + "px",
            height: img.height + "px",
            background: "100% 100% url('./css/img/" + zouti + ".svg')",
            transform: "rotate(" + r + "deg) scale(" + s + ")"
          });
        };
        return img.src = "./css/img/" + zouti + ".svg";
      };
      this.id = UNIQUE_ID++;
      creation(this.id, this.zouti, $("#Zouti"), SCALE, ROTATION);
      switch (this.zouti) {
        case "pied-a-coulisse":
          id = UNIQUE_ID++;
          creation(id, "coulisse", $("#" + this.id), 1, 0);
          $("#" + id).draggable({
            axis: "x",
            containment: "parent"
          });
      }
      offset = $("#" + this.id).offset();
      $("#" + this.id).css({
        top: -offset.top,
        left: -offset.left
      }).draggable({
        start: function(event, ui) {
          return up($(this));
        }
      });
      up($("#" + this.id));
    }

    return Zouti;

  })();

  $(function() {
    var j, len, zouti;
    videoElement = $('video')[0];
    audioSelect = $('select#audioSource')[0];
    videoSelect = $('select#videoSource')[0];
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;
    if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
      alert('This browser does not support MediaStreamTrack.\n\nTry Chrome.');
    } else {
      MediaStreamTrack.getSources(gotSources);
    }
    $(audioSelect).on("change", function() {
      return start();
    });
    $(videoSelect).on("change", function() {
      return start();
    });
    $("#cam, .local, #menu-div, #delete").hide();
    $("#menu-div, #menu").draggable();
    $("#menu, #menu-close").on("click", function() {
      return $("#menu-div").toggle();
    });
    $("#zouti-close").on("click", function() {
      return $("#Zouti").toggle();
    });
    $("#source-toggle").on("click", function() {
      return $(".web, .local, #cam, #web-iframe").toggle();
    });
    $("#web-go").on("click", function() {
      return $("#web-iframe").attr("src", $("#web-url").val());
    });
    $("body").on("click", ".zouti", function() {
      return up($(this));
    });
    $("body").on("click", "#delete", function() {
      var id;
      id = $(this).attr('data-id');
      $("#" + id).css({
        visibility: "hidden"
      });
      return $(this).hide();
    });
    for (j = 0, len = ZOUTI.length; j < len; j++) {
      zouti = ZOUTI[j];
      $("#menu-div").append("<button id='create-" + zouti + "' data-zouti='" + zouti + "'>" + zouti + "</button>");
      $("#create-" + zouti).on("click", function() {
        return new Zouti($(this).attr("data-zouti"));
      });
    }
    $("#slider-s").slider({
      value: SCALE,
      min: 0.1,
      max: 4,
      step: 0.01,
      slide: function(event, ui) {
        SCALE = ui.value;
        $("#scale-info").html("x" + SCALE);
        return $('.selected').css('transform', "rotate(" + ($('.selected').attr('data-rotation')) + "deg) scale(" + SCALE + ")").attr("data-scale", "" + SCALE);
      }
    });
    return $("#slider-r").slider({
      value: ROTATION,
      orientation: "vertical",
      min: -180,
      max: 180,
      step: 1,
      slide: function(event, ui) {
        ROTATION = ui.value;
        $("#rotation-info").html(ROTATION + "°");
        return $('.selected').css('transform', "rotate(" + ROTATION + "deg) scale(" + ($('.selected').attr('data-scale')) + ")").attr("data-rotation", "" + ROTATION);
      }
    });
  });

}).call(this);
